[package]
name = "mcw"
version = "0.3.0"
edition = "2021"
# Multi command wizard
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.6"
walkdir = "2.3.3"
colored = "2.0.0"
tui = "0.19.0"
crossterm = "0.26.1"
